// Package store owns the SQLite database: schema migrations (goose, embedded)
// and two connection pools over the same file —
//
//   - a read pool (several connections, query_only) for request handlers and
//     badge resolution; WAL lets these run while a write is in progress;
//   - a single write connection, so writers queue inside database/sql instead
//     of contending for SQLite's lock (no SQLITE_BUSY between our own writes).
//
// Queries are generated by sqlc into package db (see queries.sql).
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"runtime"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite" // registers the "sqlite" driver

	"github.com/FelisCatusKR/chzzk-djclass-chat/internal/store/db"
)

//go:embed migrations/*.sql
var migrations embed.FS

// ErrNestedWrite is returned when WriteTx is called from inside another
// WriteTx: the only write connection is already held, so it would deadlock.
var ErrNestedWrite = errors.New("store: nested WriteTx (the single write connection is held)")

type Store struct {
	readDB  *sql.DB
	writeDB *sql.DB

	// Read runs queries on the read-only pool.
	Read *db.Queries
}

// Open opens (creating if needed) the database at path and applies pending
// migrations. path must be a real file: WAL does not work for in-memory DBs.
func Open(ctx context.Context, path string) (*Store, error) {
	// busy_timeout still matters for the read pool and for other processes
	// (e.g. a backup) touching the file.
	common := "_pragma=busy_timeout(5000)&_pragma=foreign_keys(1)"

	writeDB, err := sql.Open("sqlite", fmt.Sprintf(
		"file:%s?%s&_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)&_txlock=immediate",
		path, common))
	if err != nil {
		return nil, err
	}
	writeDB.SetMaxOpenConns(1)
	writeDB.SetMaxIdleConns(1)
	writeDB.SetConnMaxLifetime(0)

	if err := migrate(ctx, writeDB); err != nil {
		writeDB.Close()
		return nil, err
	}

	readDB, err := sql.Open("sqlite", fmt.Sprintf(
		"file:%s?%s&_pragma=query_only(1)", path, common))
	if err != nil {
		writeDB.Close()
		return nil, err
	}
	n := max(4, runtime.NumCPU())
	readDB.SetMaxOpenConns(n)
	readDB.SetMaxIdleConns(n)

	return &Store{readDB: readDB, writeDB: writeDB, Read: db.New(readDB)}, nil
}

func migrate(ctx context.Context, conn *sql.DB) error {
	fsys, err := fs.Sub(migrations, "migrations")
	if err != nil {
		return err
	}
	p, err := goose.NewProvider(goose.DialectSQLite3, conn, fsys)
	if err != nil {
		return fmt.Errorf("store: migrations: %w", err)
	}
	if _, err := p.Up(ctx); err != nil {
		return fmt.Errorf("store: migrate: %w", err)
	}
	return nil
}

type writeKey struct{}

// WriteTx runs fn in a BEGIN IMMEDIATE transaction on the single write
// connection, committing if fn returns nil. Inside fn, use the given ctx and q
// only. Keep fn short and never do network I/O in it: every other writer waits
// for it. Calling WriteTx again with fn's ctx returns ErrNestedWrite.
func (s *Store) WriteTx(ctx context.Context, fn func(ctx context.Context, q *db.Queries) error) (err error) {
	if ctx.Value(writeKey{}) != nil {
		return ErrNestedWrite
	}
	tx, err := s.writeDB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()
	if err = fn(context.WithValue(ctx, writeKey{}, true), db.New(tx)); err != nil {
		return err
	}
	return tx.Commit()
}

// ReadDB and WriteDB expose the pools for libraries that need a *sql.DB
// (e.g. the session store). Prefer Read / WriteTx everywhere else.
func (s *Store) ReadDB() *sql.DB  { return s.readDB }
func (s *Store) WriteDB() *sql.DB { return s.writeDB }

func (s *Store) Close() error {
	return errors.Join(s.readDB.Close(), s.writeDB.Close())
}
