# Generated by Django 6.0.6 on 2026-06-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varchivetoken',
            name='token_encrypted',
        ),
        migrations.AddField(
            model_name='varchivetoken',
            name='varchive_user_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
