// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Channel struct {
	ID                    int64
	UserID                int64
	ChzzkChannelID        string
	AccessTokenEncrypted  *string
	RefreshTokenEncrypted *string
	TokenExpiresAt        *int64
	CreatedAt             int64
}

type DjClass struct {
	ID                int64
	UserID            int64
	Button            int64
	DjClass           string
	DjPowerSum        *float64
	MaxDjPower        *float64
	DjPowerConversion *float64
	SyncedAt          int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID              int64
	ChzzkID         string
	ChzzkNickname   string
	PreferredButton *int64
	CreatedAt       int64
}

type VarchiveLink struct {
	ID               int64
	UserID           int64
	VarchiveNickname string
	VarchiveUserNo   *int64
	IsActive         bool
	CreatedAt        int64
	UpdatedAt        int64
}
