# Generated by Django 6.0.6 on 2026-06-22 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.PositiveSmallIntegerField()),
                ('dj_class', models.CharField(max_length=64)),
                ('dj_power_sum', models.FloatField(blank=True, null=True)),
                ('max_dj_power', models.FloatField(blank=True, null=True)),
                ('dj_power_conversion', models.FloatField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dj_classes',
                'constraints': [models.UniqueConstraint(fields=('user', 'button'), name='uniq_user_button'), models.CheckConstraint(condition=models.Q(('button__in', [4, 5, 6, 8])), name='button_valid')],
            },
        ),
    ]
