// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getChannelByChzzkID = `-- name: GetChannelByChzzkID :one
SELECT id, user_id, chzzk_channel_id, access_token_encrypted, refresh_token_encrypted, token_expires_at, created_at FROM channels WHERE chzzk_channel_id = ?
`

func (q *Queries) GetChannelByChzzkID(ctx context.Context, chzzkChannelID string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByChzzkID, chzzkChannelID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChzzkChannelID,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByChzzkID = `-- name: GetUserByChzzkID :one
SELECT id, chzzk_id, chzzk_nickname, preferred_button, created_at FROM users WHERE chzzk_id = ?
`

func (q *Queries) GetUserByChzzkID(ctx context.Context, chzzkID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByChzzkID, chzzkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChzzkID,
		&i.ChzzkNickname,
		&i.PreferredButton,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByNickname = `-- name: GetUserByNickname :one
SELECT id, chzzk_id, chzzk_nickname, preferred_button, created_at FROM users WHERE chzzk_nickname = ? ORDER BY id LIMIT 1
`

// Several users can share a nickname; take the oldest, deterministically.
func (q *Queries) GetUserByNickname(ctx context.Context, chzzkNickname string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByNickname, chzzkNickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChzzkID,
		&i.ChzzkNickname,
		&i.PreferredButton,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveLink = `-- name: HasActiveLink :one
SELECT EXISTS (
    SELECT 1 FROM varchive_links WHERE user_id = ? AND is_active = 1
) AS has_link
`

func (q *Queries) HasActiveLink(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveLink, userID)
	var has_link bool
	err := row.Scan(&has_link)
	return has_link, err
}

const listDjClasses = `-- name: ListDjClasses :many
SELECT id, user_id, button, dj_class, dj_power_sum, max_dj_power, dj_power_conversion, synced_at FROM dj_classes WHERE user_id = ? ORDER BY button
`

func (q *Queries) ListDjClasses(ctx context.Context, userID int64) ([]DjClass, error) {
	rows, err := q.db.QueryContext(ctx, listDjClasses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DjClass
	for rows.Next() {
		var i DjClass
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Button,
			&i.DjClass,
			&i.DjPowerSum,
			&i.MaxDjPower,
			&i.DjPowerConversion,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPreferredButton = `-- name: SetPreferredButton :exec
UPDATE users SET preferred_button = ? WHERE id = ?
`

type SetPreferredButtonParams struct {
	PreferredButton *int64
	ID              int64
}

func (q *Queries) SetPreferredButton(ctx context.Context, arg SetPreferredButtonParams) error {
	_, err := q.db.ExecContext(ctx, setPreferredButton, arg.PreferredButton, arg.ID)
	return err
}

const updateChannelTokens = `-- name: UpdateChannelTokens :exec
UPDATE channels
SET access_token_encrypted = ?, refresh_token_encrypted = ?, token_expires_at = ?
WHERE id = ?
`

type UpdateChannelTokensParams struct {
	AccessTokenEncrypted  *string
	RefreshTokenEncrypted *string
	TokenExpiresAt        *int64
	ID                    int64
}

func (q *Queries) UpdateChannelTokens(ctx context.Context, arg UpdateChannelTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelTokens,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.ID,
	)
	return err
}

const upsertChannel = `-- name: UpsertChannel :exec
INSERT INTO channels (user_id, chzzk_channel_id, access_token_encrypted, refresh_token_encrypted, token_expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    chzzk_channel_id        = excluded.chzzk_channel_id,
    access_token_encrypted  = excluded.access_token_encrypted,
    refresh_token_encrypted = excluded.refresh_token_encrypted,
    token_expires_at        = excluded.token_expires_at
`

type UpsertChannelParams struct {
	UserID                int64
	ChzzkChannelID        string
	AccessTokenEncrypted  *string
	RefreshTokenEncrypted *string
	TokenExpiresAt        *int64
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannel,
		arg.UserID,
		arg.ChzzkChannelID,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
	)
	return err
}

const upsertDjClass = `-- name: UpsertDjClass :exec
INSERT INTO dj_classes (user_id, button, dj_class, dj_power_sum, max_dj_power, dj_power_conversion)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, button) DO UPDATE SET
    dj_class            = excluded.dj_class,
    dj_power_sum        = excluded.dj_power_sum,
    max_dj_power        = excluded.max_dj_power,
    dj_power_conversion = excluded.dj_power_conversion,
    synced_at           = unixepoch()
`

type UpsertDjClassParams struct {
	UserID            int64
	Button            int64
	DjClass           string
	DjPowerSum        *float64
	MaxDjPower        *float64
	DjPowerConversion *float64
}

func (q *Queries) UpsertDjClass(ctx context.Context, arg UpsertDjClassParams) error {
	_, err := q.db.ExecContext(ctx, upsertDjClass,
		arg.UserID,
		arg.Button,
		arg.DjClass,
		arg.DjPowerSum,
		arg.MaxDjPower,
		arg.DjPowerConversion,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (chzzk_id, chzzk_nickname)
VALUES (?, ?)
ON CONFLICT (chzzk_id) DO UPDATE SET chzzk_nickname = excluded.chzzk_nickname
RETURNING id, chzzk_id, chzzk_nickname, preferred_button, created_at
`

type UpsertUserParams struct {
	ChzzkID       string
	ChzzkNickname string
}

// Queries for the realtime path (ingestor tokens, badge resolution) and login.
// Link / sync / dashboard queries are added with those features.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.ChzzkID, arg.ChzzkNickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ChzzkID,
		&i.ChzzkNickname,
		&i.PreferredButton,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVarchiveLink = `-- name: UpsertVarchiveLink :exec
INSERT INTO varchive_links (user_id, varchive_nickname, varchive_user_no)
VALUES (?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    varchive_nickname = excluded.varchive_nickname,
    varchive_user_no  = excluded.varchive_user_no,
    is_active         = 1,
    updated_at        = unixepoch()
`

type UpsertVarchiveLinkParams struct {
	UserID           int64
	VarchiveNickname string
	VarchiveUserNo   *int64
}

func (q *Queries) UpsertVarchiveLink(ctx context.Context, arg UpsertVarchiveLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertVarchiveLink, arg.UserID, arg.VarchiveNickname, arg.VarchiveUserNo)
	return err
}
